 version: '3'
 services:
  adidas-eureka-service:
     image: adidas-eureka-service:0.0.1-SNAPSHOT
     #ports:
      #- 3001:8761
  adidas-public-service:
    image: adidas-public-service:0.0.1-SNAPSHOT
    ports:
     - 3000:8989
    environment:
     - EUREKA_HOST=adidas-eureka-service
     - EUREKA_PORT=8761
  adidas-subscription-service:
    image: adidas-subscription-service:0.0.1-SNAPSHOT
    #ports:
     #- 3002:7777
    environment:
     - EUREKA_HOST=adidas-eureka-service
     - EUREKA_PORT=8761
  adidas-email-service:
    image: adidas-email-service:0.0.1-SNAPSHOT
    #ports:
     #- 3003:8888
    environment:
     - EUREKA_HOST=adidas-eureka-service
     - EUREKA_PORT=8761