logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true  
      routes:
        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subscriptions/**
          metadata:
            response-timeout: 2000
            connect-timeout: 2000
          filters:
            - name: CircuitBreaker
              args:
                name: subscription-service
                fallbackuri: forward:/subscriptionFallBack
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email/**
          metadata:
            response-timeout: 6000
            connect-timeout: 2000  
          filters:
            - name: CircuitBreaker
              args:
                name: email-service
                fallbackuri: forward:/emailFallback
        - id: registry-service
          uri: lb://EUREKA-SERVICE
          predicates:
            - Path=/registry/**
          metadata:
            response-timeout: 60000
            connect-timeout: 20000  
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: registry-service
                fallbackuri: forward:/eurekaFallback
        - id: eureka-service
          uri: lb://EUREKA-SERVICE
          predicates:
            - Path=/eureka/**
          metadata:
            response-timeout: 60000
            connect-timeout: 20000  
          filters:
            - name: CircuitBreaker
              args:
                name: eureka-service
                fallbackuri: forward:/eurekaFallback

eureka:
  instance:
    hostname: ${HOSTNAME:localhost} 
  client:
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/    
               
server:
  port: 8989
