server:
  port: 8888
spring:
  application:
    name: EMAIL-SERVICE


eureka:
  instance:
    hostname: ${HOSTNAME:localhost} 
  client:
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/    
